repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        exclude: dags/
        args: ["--py311-plus"]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln
        args: [--config=./pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: ["--config=./pyproject.toml"]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        args:
          [--disable=MD013, --disable=MD033, --disable=MD050, --disable=MD052]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=./.flake8"]
        additional_dependencies:
          [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-encodings",
            "flake8-implicit-str-concat",
            "flake8-mutable",
            "flake8-noqa",
            "flake8-print",
            "flake8-return",
            "flake8-secure-coding-standard",
            "flake8-simplify",
            "flake8-type-checking",
            "flake8-use-fstring",
            "flake8-use-pathlib",
          ]
  - repo: https://github.com/dosisod/refurb
    rev: v1.10.0
    hooks:
      - id: refurb
        args: [--ignore, "120", --ignore, "128"]
        additional_dependencies: [pydantic==1.10.4, sqlalchemy==1.4.46]
  - repo: https://github.com/pycqa/pylint
    rev: "v2.15.5"
    hooks:
      - id: pylint
        exclude: "^(test_*|dags)/"
        additional_dependencies:
          [
            algoliasearch==2.6.3,
            beautifulsoup4==4.11.1,
            loguru==0.6.0,
            numpy==1.24.1,
            pandas==1.5.3,
            paramiko==2.12.0,
            pydantic==1.10.4,
            reportlab==4.2.5,
            requests==2.28.2,
            sendgrid==6.9.7,
            sqlalchemy==1.4.46,
            sqlalchemy2-stubs==0.0.2a32,
            typer==0.6.1,
            zeep==4.2.1,
          ]
        args:
          [
            "--extension-pkg-whitelist=lxml.etree",
            "--disable=c-extension-no-member",
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
        exclude: dags/
        args: [--show-traceback, --pdb]
        additional_dependencies:
          [
            loguru==0.6.0,
            loguru-mypy==0.0.4,
            numpy==1.24.1,
            pandas-stubs==1.5.2.230105,
            pydantic==1.10.4,
            sqlalchemy==1.4.46,
            sqlalchemy2-stubs==0.0.2a32,
            typer==0.6.1,
            types-paramiko==2.12.0.3,
            types-requests==2.28.11.8,
            google-auth==2.37.0,
            google-auth-stubs==0.3.0,
            google-api-python-client==2.159.0,
            google-api-python-client-stubs==1.28.0,
          ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.290
    hooks:
      - id: pyright
        additional_dependencies:
          [
            algoliasearch==2.6.3,
            beautifulsoup4==4.11.1,
            loguru==0.6.0,
            numpy==1.24.1,
            pandas==1.5.3,
            paramiko==2.12.0,
            pydantic==1.10.4,
            requests==2.28.2,
            sendgrid==6.9.7,
            sqlalchemy==1.4.46,
            typer==0.6.1,
            zeep==4.2.1,
            google-auth==2.37.0,
            google-api-python-client==2.159.0,
          ]
