repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args: ["--py311-plus"]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]

  # (Opcional) Si quieres mantener pycln, usa una versión estable
  # - repo: https://github.com/hadialqattan/pycln
  #   rev: v2.2.2
  #   hooks:
  #     - id: pycln

  - repo: https://github.com/dosisod/refurb
    rev: v2.0.0
    hooks:
      - id: refurb

  - repo: https://github.com/pycqa/pylint
    rev: v3.2.7
    hooks:
      - id: pylint
        additional_dependencies:
          - typer>=0.12.0
          - loguru>=0.7.0
          - pydantic-settings>=2.11.0
          - sqlalchemy>=2.0.0
          - pandas>=2.3.0
          - requests>=2.31.0

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args:
          - "--config-file=pyproject.toml"
          - "--install-types"
          - "--non-interactive"
          - "--ignore-missing-imports"

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.407
    hooks:
      - id: pyright
        args: ["--project=pyproject.toml"]
        additional_dependencies:
          - pydantic>=2.0
          - pydantic-settings>=2.0
          - sqlalchemy>=2.0
          - typer>=0.12.0
          - loguru>=0.7.0
          - requests>=2.31.0
